baseurl = "/"           # The base URL of your Hugo site
title = "Michigan Math Corps"     # The title of your Hugo site
author = "Wes Jackson and Margaret Rudnick"   # The author name
googleAnalytics = ""    # Your Google Analytics tracking ID
enableRobotsTXT = true
language = "en-US"
paginate = 7            # The numbers of posts per page
theme = "terrassa"      # Your Hugo theme

[params.cta] # Call To Action
    show = true
    cta = "Contact"  # Text message of the CTA
    link = "contact" # Relative URL
