baseurl = "/"           # The base URL of your Hugo site
title = "Michigan Math Corps"     # The title of your Hugo site
author = "Wes Jackson and Margaret Rudnick"   # The author name
googleAnalytics = ""    # Your Google Analytics tracking ID
enableRobotsTXT = true
language = "en-US"
paginate = 7            # The numbers of posts per page
theme = "terrassa"      # Your Hugo theme

[params]
	description = ""
	favicon = "favicon.ico"
	logo = "math-logo.png"

[params.cta] # Call To Action
    show = true
    cta = "Donate"  # Text message of the CTA
    link = "https://leadersandbest.umich.edu/find/#!/give/basket/fund/335705" # Absolute URL

[params.contact]
    email = "kochsc@umich.edu"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.separator]
    show = true

[params.form] # Contact form
    netlify = false
    action = "https://formspree.io/xvogppzo"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Message"
    inputMsgLength = 750
    inputSubmitValue = "Send"
